yeatmanlab/roar-dashboard

- src/pages/Participant.vue
- src/router/index.js
Just created an empty participant page to add a new route.
> Add a new route for the participant dashboard

- src/components/ReportSWR.vue
- src/components/reportMarkdownSWR.js
Added 1st grade graphs
Updated colors, titles, axis, etc., for graphs 2-5.
Changed SWR report font to Helvetica Neue
> SWR Graph updates

- src/components/RoarDataTable.vue
- src/components/query/TableRunResults.vue
This PR improves quality of life for users of the DataTable. 
[x] Broaden methods of data input (allow nested objects as the field key)
[x] Add pagination
- Automatically added for records over 10
- Dropdown to change pagination for 10, 20, 50
[x] Clean up export
- Use built in method, eases need for custom solutions for data formatting
> Datatable pagination

- .firebaserc
- src/components/Navbar.vue
- src/pages/Participant.vue
- src/pages/SignIn.vue
- src/router/index.js
- src/store/auth.js
In my local testing, this PR, along with [roar-firekit PR 32](https://github.com/yeatmanlab/roar-firekit/pull/32) resolves the reauthentication issue that we were experiencing yesterday.
> Use pinia subscribe to detect auth status in SignIn.vue

- src/router/index.js
Defines routes that require admin status. I would love input on the behavior when an unauthorized user tries to access a page. Right now it just sends them to the dynamic homepage (in the case of un-admin users, just the participant view).
I am open to discussion!
> Define routes that require admin status

- src/pages/MassUploader.vue
This PR primarily makes the mass uploader more user-friendly in line with requests from partnerships. 
In this PR:
- Remove orgs dropdown section from the mass uploader
- Adds orgs category in MU dropdowns
- Adds support for checking whether an org is valid (against orgs the user is allowed to create for) before submitting.
- If not valid, added to the error users table with relevant message.
- Adds 'ignore this column' as dropdown item.
> Add Orgs as dropdown options on the mass uploader

- src/router/index.js
- src/store/auth.js
Adds route guards to paths that should be restricted to super admins (For now, that is our lab users.) 
I think I got all of the relevant routes but please check to make sure. 
Resolves Issue #43
> Add super admin check

- src/pages/MassUploader.vue
Fixes issue where no groups are valid in mass uploader.
> Fix getGroupId function

- package-lock.json
- package.json
- src/pages/RegisterStudents.vue
This PR requires that [roar-firekit PR47](https://github.com/yeatmanlab/roar-firekit/pull/47) be merged and a new version of firekit is published before it will work
> Pass id and abbreviation to register students methods

- src/pages/RegisterStudents.vue
This PR adds
- Route away from the page ONLY when all successful users finish processing
- Toast for upload file, successful creation, failed creation
- Have button be unclickable while creations are processing
> Mass Uploader Refinements 

- src/components/GameTabs.vue
- src/components/tasks/PA.vue
- src/components/tasks/SRE.vue
- src/components/tasks/SWR.vue
- src/pages/Participant.vue
- src/store/auth.js
Implements two requests:
- Support dynamic sequential administrations
- Only allow users to replay games after completing all games
EDIT: I was able to implement a reliable way to route to home when the page reloads, so I've included that as well in this PR.
> Game Tab Features

- src/assets/styles/components/tabview-games.scss
- src/components/reports/ReportSWR.vue
Adjust font sizing, some spacing, and a few other small tweaks for enhancement
> CSS adjustments for GameTabs

- src/components/ConsentModal.vue
- src/components/CreateOrgs.vue
- src/components/auth/SignIn.vue
Remove an unnecessary v-if statement that was causing districts and groups not to show up in the create orgs form.
> Show districts and groups

- package-lock.json
- package.json
- src/components/ListOrgs.vue
- src/components/ListUsers.vue
- src/components/RoarDataTable.vue
- src/pages/RegisterStudents.vue
- src/router/index.js
- src/router/sidebarActions.js
- src/store/auth.js
This PR implements the list-users page in admin view.
> View Users

- src/components/ListUsers.vue
- src/router/index.js
Yesterday when I tried this method, I think it coincided with another bug, causing me to believe this method didn't work.
> Use props rather than router params

- package-lock.json
- package.json
- src/components/tasks/Letter.vue
This is a copy of the other files, pa, sre, and swr. check against them to check the code to make sure everything is ported correctly
> Add roar letter handler

- src/components/tasks/Letter.vue
- src/components/tasks/PA.vue
- src/components/tasks/SRE.vue
- src/components/tasks/SWR.vue
- src/router/index.js
This PR prevents the SRE age form from showing up. The app requires ageMonth and ageYear to be able to calculate scores correctly. These fields were added in this PR. 
Also, this PR adds a route to roar-letter, and changes a bit of the v-if logic to prevent the game from trying to mount the game on an unready div.
> SRE Survey fix

- src/components/CreateAdministration.vue
I believe this will fix the incorrect invalid dates message while preserving the guard against single date entries.
> Return boolean value

- src/components/tasks/Letter.vue
- src/components/tasks/PA.vue
- src/components/tasks/SRE.vue
- src/components/tasks/SWR-ES.vue
- src/components/tasks/SWR.vue
This PR requires [roar-firekit PR 57](https://github.com/yeatmanlab/roar-firekit/pull/57) to be merged/published first.
> Select best run if user unloads the page during a game

- package-lock.json
- package.json
- src/components/ConsentModal.vue
- src/firebaseInit.js
- src/pages/Home.vue
- src/pages/Participant.vue
- src/pages/SignIn.vue
- src/store/auth.js
This PR hard-codes a delay on the consent modal to allow the firestore use doc to be updated with assignedAssignments. Hacky but works for now.
> Fix clever first login

- src/pages/CleverLanding.vue
- src/pages/SignIn.vue
- src/router/index.js
- src/store/auth.js
This PR implements a secondary loading page for clever users, a place for them to land and wait for their user docs to be filled in.
> Implement loading page for clever users

- src/pages/RegisterStudents.vue
We encountered a rate limit with creating more than x number of students a second from a single IP. So this PR introduces a timed chunking system for registration. Currently, 10 students will start the create process every second. I am open to discussion on the actual rate.
> Implement chunking for register student

- src/components/GameTabs.vue
Improves update behavior when switching between accounts. Also improves behavior for non sequential admins not correctly identifying the next game.
> Better locking behavior

- src/pages/ScoreReport.vue
This PR adds the school column. I will be using a similar pattern to add classes, however that comes with some extra logic to cull classes when several are present.
> Score report School Column

- src/components/GameTabs.vue
Changing the logic for external tasks to mark them as complete on launch.
> External Task completion

- package-lock.json
- package.json
- src/pages/ScoreReport.vue
Update fields in score report to conform to new lookup table values
> Update scores to new lookup table

- src/assets/styles/components/button.scss
- src/pages/ScoreReport.vue
Adjust css on admin sidebar button so that text is centered, and remove some unused css classes.
> [Enh] CSS Adjustments

- src/components/tasks/RegisterTask.vue
- src/helpers/query/tasks.js
- Use tanstack/query to retrieve tasks.
- Add a checkbox to toggle only registered tasks.
> Use REST API to get tasks

- src/pages/AdministrationProgress.vue
- src/pages/ScoreReport.vue
Implements defaulting behavior when tasks don't have a proper entry in the displayNames object
> Implement defaulting behavior for displayNames

- src/pages/ScoreReport.vue
A quick PR to add a sentence of info to each task card explaining the raw score to the user.
> Add raw score ranges to report

- .gitignore
- package-lock.json
- package.json
This PR updates the Roar-Multichoice NPM package to the latest version, 1.2.0.
> Update Roar-Multichoice NPM Version

- package-lock.json
- package.json
This PR updates the dashboard to use the latest version of Roar-SWR 1.1.19
> Update Roar-SWR NPM Version

- package-lock.json
- package.json
This PR updates the dashboard to use the latest version of Roar-Letter 1.1.9
> Update Roar-Letter NPM Version

- package-lock.json
- package.json
This PR updates Roar SWR to the latest version 1.1.20
> Roar SWR NPM Version Update

- package-lock.json
- package.json
This PR updates Roar Letter to the latest version 1.1.10
> Roar Letter NPM Version Update

- package-lock.json
- package.json
updating all games in package json
> updating all games to new version

- package-lock.json
- package.json
- src/App.vue
- src/components/tasks/TaskFluency.vue
- src/router/index.js
This PR adds support for ROAM Fluency as a Dashboard game.
> Add ROAM Fluency to Dashboard

- firebase/admin/.firebaserc
- firebase/admin/firestore.indexes.json
- firebase/assessment/.firebaserc
- firebase/assessment/firestore.indexes.json
- package-lock.json
- src/components/RoarDataTable.vue
- src/helpers/query/assignments.js
- src/helpers/query/utils.js
- src/pages/ScoreReport.vue
PR to enable filtering on scores fields in the score report. 
To still be done before merging:
[ ] merge this PR with main to sync changes with the linting PR
To still be done in a separate PR:
[ ] filtering on user data fields
[ ] sorting on all fields
> Score Report Filtering

- package-lock.json
- src/components/tasks/TaskFluency.vue
- src/components/tasks/TaskLetter.vue
- src/components/tasks/TaskMultichoice.vue
- src/components/tasks/TaskPA.vue
- src/components/tasks/TaskSWR-ES.vue
- src/components/tasks/TaskSWR.vue
- src/components/tasks/TaskVocab.vue
- src/pages/ScoreReport.vue
This PR is required to fix the recurrent score report issues we have been seeing.
- https://github.com/yeatmanlab/roar/issues/119
- https://github.com/yeatmanlab/roar/issues/131
- https://github.com/yeatmanlab/roar/issues/135
- https://github.com/yeatmanlab/roar/issues/139
It also requires some companion PRs in the ROAR apps.
> Correctly pass grade into all of the apps

- .github/workflows/firebase-hosting-staging.yml
- src/config/firebase.js
This PR dynamically adjusts the auth domain in the staging environment. I believe that this is necessary to make clever auth work on the staging environment.
> Change auth domain on staging environment

- src/helpers/reports.js
- src/pages/ScoreReport.vue
This PR:
- Adds CVA as a named task
- creates a task exclude list for score reports. Items added will not be shown on score reports.
> Filter out tasks on the exclude lists

- src/components/reports/tasks/TaskReport.vue
Updates task descriptions with old text
> Update task descriptions

- src/assets/NextSteps.pdf
- src/pages/ScoreReport.vue
changing the next steps text and adding the PDF requested by Alby
> Adding PDF to read more in score reports

- src/assets/styles/components/speeddial.scss
- src/components/CardAdministration.vue
- src/components/NavBar.vue
- src/pages/HomeParticipant.vue
Making Dashboard view more compact
> Compact view on Dashboard

- src/components/RoarDataTable.vue
- src/components/reports/tasks/TaskReport.vue
- src/helpers/reports.js
- src/pages/ScoreReport.vue
Updating ROAR-Letter to ROAR-Letter Names and Sounds across administration card, subscore tables, score tables, and task reports
> Update letter public facing name

- src/pages/ScoreReport.vue
This PR includes the administration name in the score report for better clarity.
> Add administration name under org name in score report

- src/assets/styles/components/tabview.scss
- src/assets/styles/theme-tailwind.css
Making header bigger and tabs in panels more visible
> Headers and Panels update

- src/components/RoarDataTable.vue
- src/components/reports/tasks/TaskReport.vue
This @change wasn't suppose to be on TaskReport
> Deleting handleModeChange

- package-lock.json
- package.json
Update Roar Multichoice npm version
> Update Roar Multichoice

- src/assets/styles/components/datatable.scss
- src/assets/styles/theme-tailwind.css
- src/components/RoarDataTable.vue
- src/pages/ScoreReport.vue
Button to compress/expand the rows on a table for preference
> Compress of Expand Tables in Dashboard

- src/components/GameTabs.vue
Adding sequential checking on the games array
> Fixing the sequential disableproperty

- src/components/RoarDataTable.vue
- src/pages/ScoreReport.vue
Moving dropdown closer to the table and to the right as requested
> Moving support level dropdown view

- src/assets/styles/components/datatable.scss
- src/assets/styles/components/dataview.scss
- src/assets/styles/theme-tailwind.css
- src/components/RoarDataTable.vue
I needed to make the paginator + view support level as a group and column-flex them
> Fixing paginator

- .github/workflows/deploy-firebase-test-cypress.yml
This PR updates the GH action to capture the title, PR number, and commit SHA in the Cypress cloud run.
> Update GH Action

- src/assets/styles/components/selectbutton.scss
- src/components/reports/DistributionChartFacet.vue
- src/components/reports/DistributionChartSupport.vue
- src/components/reports/tasks/TaskReport.vue
- src/pages/ScoreReport.vue
This PR addresses the following tickets:
> Distribution Graph Enhancements

- src/components/RoarDataTable.vue
- src/components/reports/DistributionChartSupport.vue
- src/helpers/query/assignments.js
- src/pages/ScoreReport.vue
Fixes sorting for support level distribution graph
> Update sorting criteria

- src/components/tasks/TaskFluency.vue
- src/components/tasks/TaskLetter.vue
- src/components/tasks/TaskMultichoice.vue
- src/components/tasks/TaskPA.vue
- src/components/tasks/TaskSRE.vue
- src/components/tasks/TaskSWR-ES.vue
- src/components/tasks/TaskSWR.vue
- src/components/tasks/TaskVocab.vue
- src/pages/HomeSelector.vue
Also change `let roarApp` to `const roarApp` in the task components.
> Update timeout to 20 minutes

- .github/workflows/deploy-firebase-test-cypress.yml
- cypress.config.js
- cypress/e2e/participant/playButtonGames.cy.js
- cypress/e2e/participant/playPA.cy.js
- cypress/e2e/partner-admin/listOrgs.spec.cy.js
- cypress/support/helperFunctions/roar-pa/paHelpers.js
- package-lock.json
This PR updates the Cypress test suite and adds retries to the Cypress config in order to start tracking flaky tests in the Cypress cloud.
> Update Cypress Tests

- src/components/GameTabs.vue
Removes an errant `&&` that was affecting the automated deploy and build.
> Fix Gametabs Bug

- src/pages/ScoreReport.vue
Fix a copy and paste error where the info text for Score Report showed Progress Report
> Update Score Report Text

- src/components/auth/SignIn.vue
- src/translations/es/es-componentTranslations.json
Unclear note showing up in password box [https://github.com/yeatmanlab/roar/issues/197](https://github.com/yeatmanlab/roar/issues/197)
> Fixing issue 197

- cypress/e2e/participant/network-tests/roar-swr/playSWR-2G.cy.js
- cypress/e2e/participant/network-tests/roar-swr/playSWR-3G.cy.js
- cypress/e2e/participant/network-tests/roar-swr/playSWR-HighLatency.cy.js
This PR updates the suite of network tests that run on dashboard release.
> Update Network Tests

- package-lock.json
- package.json
This PR updates SRE and Letter to the latest versions.
> Update ROAR-SRE and ROAR-Letter for internationalization

- package-lock.json
- package.json
> Bumping letter

- cypress/e2e/participant/default-tests/playFluency-ARF.cy.js
- package-lock.json
- package.json
This PR updates all Roar Apps to their latest versions.
> Update Roar Apps

- package-lock.json
- package.json
> Bumping letter letra

- cypress/e2e/participant/default-tests/playVideo.cy.js
> Playing Video Cypress Test

- package-lock.json
- src/components/reports/IndividualScoreReportTask.vue
- src/helpers/reports.js
- src/pages/IndividualReport.vue
- src/pages/ScoreReport.vue
- Fix bug where Phoneme score wasn't displaying for kindergarteners
- Fix bug where support colors were incorrect for grades >= 6
- Update Score Text
> Individual Score Report Bug Fixes

- firebase/admin/firestore.rules
- firebase/assessment/firestore.rules
rather than custom auth claims
> Update firestore rules to check super_admin status from firestore

- src/components/GameTabs.vue
- src/components/VideoPlayer.vue
- src/pages/HomeParticipant.vue
> Add updateVideoCompletion components

- cypress.config.js
- cypress/e2e/partner-admin/default-tests/testScoreReportFiltering.cy.js
- src/components/CardAdministration.vue
- src/components/tasks/TaskLevante.vue
Change module import, remove css import
> Fix Levante Task Launcher

- cypress.config.js
- cypress/e2e/partner-admin/default-tests/testScoreReportFiltering.cy.js
- src/components/CardAdministration.vue
- src/components/reports/IndividualScoreReportTask.vue
> update optional assessments to use tagging

- src/App.vue
- src/components/CardAdministration.vue
- src/components/GameTabs.vue
- src/firebaseInit.js
By rendering the NavBar when the authStore is ready, firekit is defined and the restConfig property will exist. This allows admins to sign in without having to reload every time for the page to load.
> restConfig bug fix

- package-lock.json
- package.json
> Bumping PA

- src/components/reports/TableScoreTag.vue
- src/helpers/reports.js
- src/pages/ProgressReport.vue
- src/pages/ScoreReport.vue
- Updates raw score tags to white background
- Makes score font bold for easier readability/higher visual weight
- Fixes bug where students were getting hexa-duped in progress table
> Score Table Updates

- cypress.config.js
- src/pages/HomeParticipant.vue
adding public facing names to participant view and fix box position
> Public facing names to participant view

- package-lock.json
- package.json
- src/components/GameTabs.vue
- src/components/tasks/TaskLevante.vue
- src/translations/es/es-componentTranslations.json
- Adding Spanish translations for LEVANTE tasks
-  Changing how task name and description is computed
- Updating core-tasks version
> Changes for LEVANTE Spanish task versions

- .github/workflows/deploy-firebase-test-cypress.yml
- .github/workflows/firebase-hosting-production.yml
- .github/workflows/firebase-hosting-staging.yml
Increase heap size to 8 MB when building project.
> Increase Node Memory

- src/helpers/query/administrations.js
making batchGet on smaller batch requests
> BatchGets on batches of 5

- src/components/auth/RegisterParent.vue
> Adding isNextButtonDisabled to the Next button

- package-lock.json
- package.json
> Bumping PA for new corpus

- src/components/reports/SubscoreTable.vue
- src/components/reports/tasks/TaskReport.vue
- src/pages/ScoreReport.vue
Also fixes a bug with frase showing `NaN` for non-completed assignments.
> Refactor Subscore Datatables to use client-side data. 

- src/assets/styles/routes/signin.scss
> Fix hiding captcha

- src/components/ParticipantSidebar.vue
- src/pages/HomeParticipant.vue
- src/pages/HomeSelector.vue
- src/sentry.js
https://www.notion.so/Disable-Sentry-for-LEVANTE-instance-7220141de3d54bcba06554536911445a
https://www.notion.so/Disable-Consent-Assent-forms-60dfd485eea14ba69d5818eec781c371
https://www.notion.so/Don-t-render-Student-Info-section-on-Child-home-page-04669919d3384f54a00f30ee64337881
> LHT-273, LHT-267: Disabling sentry and consent form for levante instance

- package-lock.json
- package.json
This PR rolls back the Core Tasks repo for compatibility with TROG/Syntax
> Roll Back Core Tasks

- package-lock.json
- package.json
Reverts yeatmanlab/roar-dashboard#587
> Revert "Core tasks verion update"

- src/components/ListOrgs.vue
- src/pages/IndividualReport.vue
- src/pages/RegisterStudents.vue
- src/pages/ScoreReport.vue
add margin to register student button
> Fix margin on register students button

- package-lock.json
- package.json
@ksmontville Can you test and make sure Syntax work as intended with the new changes?
> New version of core tasks

- src/assets/styles/theme-tailwind.css
- src/components/CardAdministration.vue
- src/helpers/plotting.js
- src/helpers/query/utils.js
- src/pages/ProgressReport.vue
- src/pages/ScoreReport.vue
> Add Progress Barcharts by task

- src/components/CardAdministration.vue
- src/components/CreateOrgs.vue
- src/components/ListOrgs.vue
- src/components/ListUsers.vue
- src/components/NavBar.vue
- src/components/OrgPicker.vue
- src/components/auth/AuthEmailLink.vue
- src/components/tasks/TaskCrowding.vue
- src/components/tasks/TaskFluency.vue
- src/components/tasks/TaskLetter.vue
- src/components/tasks/TaskLevante.vue
- src/components/tasks/TaskMultichoice.vue
- src/components/tasks/TaskPA.vue
- src/components/tasks/TaskRan.vue
- src/components/tasks/TaskSRE.vue
- src/components/tasks/TaskSWR.vue
- src/components/tasks/TaskVocab.vue
- src/pages/ClassLinkLanding.vue
- src/pages/CleverLanding.vue
- src/pages/HomeAdministrator.vue
- src/pages/HomeParticipant.vue
- src/pages/HomeSelector.vue
- src/pages/IndividualReport.vue
- src/pages/ProgressReport.vue
- src/pages/RegisterFamilyUsers.vue
- src/pages/ScoreReport.vue
- src/store/auth.js
When an SSO user logs in for the first time, they require a refresh to see their name and admin on homeParticipant. These small enhancements are thought to improve that.
> WIP: Login query improvements

- cypress/e2e/participant/default-tests/playVocab.cy.js
- cypress/support/commands.js
- package-lock.json
- package.json
Update Roar Vocab to its latest npm version.
> Update Roar Vocab

- package-lock.json
- package.json
> upgrading ran

- src/pages/LEVANTE/UserSurvey.vue
This gives user feedback if writing the survey data fails.
> Adding toast for survey error

- src/pages/RegisterFamilyUsers.vue
Small CSS fix for the modal on parent sign-up
> Center text on parent sign up modal

- src/components/auth/SignIn.vue
- src/helpers/query/utils.js
- src/pages/HomeParticipant.vue
Three minor fixes: 
- If the fetchDocById functions with missing or undefined params, throw a warn and return `{}` or `[]` rather than an axios error.
- Prevent a line from throwing unnecessary undefined errors
- Prevent auto-fill in the login email from throwing an error
These changes represent 3 small fixes, however each fix is 1-3 lines so I feel packaging them together is okay. Also, these changes are in pursuit of one goal (minimizing unnecessary Sentry errors)
> Address Sentry Errors I

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roar-pa` to 2.2.4.
> Update PA version to 2.2.4

- src/pages/HomeParticipant.vue
I believe this will fix the issue of the games tabs not appearing after each game.
Fixes: https://github.com/yeatmanlab/roar/issues/281
I understand that this change was originally made to decrease the package size of the app. However I feel that in this case, it is better to reverse the change to prevent this issue from occurring. 
My theory as to what is happening is as follows. Those two components are being imported on the onMounted hook. Vue tries to reuse components whenever possible, thus will not call the onMounted hook in every case [[1]](https://stackoverflow.com/questions/57699473/vuejs-hook-mounted-is-not-called-when-page-is-re-open-by-vue-router). There seem to be some cases where when the user navigates back to a page, …
> Fix: Blank Screen 

- cypress/support/commands.js
This PR cherry picks @ksmontville's fix for intermittently failing Cypress tests. It makes the `cy.selectAdministration` function a recursive function with up to three retries.
> Make cy.selectAdministration a recursive function with up to 3 retries.

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roam-fluency` to 1.11.21.
> Update ROAM-Fluency version to 1.11.21

- package-lock.json
- package.json
> Bumping RAN to 1.0.19

- cypress.config.js
- cypress/e2e/participant/default-tests/playSyntax.cy.js
- cypress/e2e/pre-release-tests/testOpenAdministrations.cy.js
- cypress/support/helper-functions/roar-syntax/languageOptions.js
- cypress/support/helper-functions/roar-syntax/syntaxHelpers.js
This PR builds out the infrastructure for testing Roar Syntax variants across administrations.
> Tests for Roar Syntax

- package-lock.json
- package.json
- src/components/LanguageSelector.vue
- src/main.js
- src/translations/en/en-componentTranslations.json
- src/translations/en/us/en-us-componentTranslations.json
- src/translations/es/co/es-co-componentTranslations.json
- src/translations/es/es-componentTranslations.json
- src/translations/i18n.js
- vite.config.js
This PR removes country flags from the language selector dropdown component, and replaces hyperlocal Spanish dialicts with just Spanish and Latin American general dialects.
> Remove Country Flags

- cypress.config.js
- src/components/NavBar.vue
- src/pages/NotFound.vue
- src/translations/en/en-componentTranslations.json
- src/translations/en/us/en-us-componentTranslations.json
- src/translations/es/co/es-co-componentTranslations.json
- src/translations/es/es-componentTranslations.json
> Fixing unstyled buttons

- cypress.config.js
> Changing Admin Name

- src/components/RoarDataTable.vue
- src/components/VariantCard.vue
- src/pages/HomeParticipant.vue
This PR attempts to fix an issue where Clever and ClassLink users see no assignments until page refresh.
Previously, before our consent picker refactor, the HomeSelector.vue component would wait for the `delayed` event from the ConsentModal.vue component and then refresh user docs when it received the event. After that refactor, we forgot to port that behavior into HomeParticipant.vue. This PR remedies that.
We cannot currently end-to-end test Clever or ClassLink integration.
> Add refreshDocs function to HomeParticipant.vue

- src/components/ConsentModal.vue
- src/pages/ClassLinkLanding.vue
- src/pages/CleverLanding.vue
- src/pages/HomeParticipant.vue
This is yet another attempt to fix first-time login for Clever and ClassLink users. Previously, we've left the `CleverLanding.vue` and `ClassLinkLanding.vue` pages when the user docs are found. However, this forced us to do some additional waiting for the user's assignments to be propagated from their administration. In this PR, we wait for the assignments to be found in the user docs before we leave the landing pages.
- We cannot current test identity provider (e.g., Clever or ClassLink) integration in our end-to-end tests.
- This is an urgent fix needed for Clever users running on Monday. I intend to wait for tests to pass and then bypass the review channel as it is not reasonable to demand a review on the weekend.
> Wait for assignments for Clever and ClassLink users

- package-lock.json
- package.json
- src/pages/HomeAdministrator.vue
> Fixing RAN and Crowding card-title overwriting

- src/components/reports/TableScoreTag.vue
If the rawScore === 0 then it will be displayed on the tooltip
> Adding condition to rawScores to display on tooltip

- src/components/ConsentPicker.vue
- src/components/CreateAdministration.vue
- src/pages/HomeParticipant.vue
- src/pages/HomeSelector.vue
Add option to ignore consent in create-administration form consent picker
> Add option to ignore consent in create-administration form

- src/pages/HomeSelector.vue
> re introducing timeout to 10 min

- src/pages/ClassLinkLanding.vue
- src/pages/CleverLanding.vue
This PR fixes a bug in which Clever and ClassLink users were being prematurely routed to home before their assignments were ready.
We are currently unable to test Clever/ClassLink integration in our end-to-end testing suite.
> Check if user is undefined/null before routing to home in CleverLanding.vue and ClassLinkLanding.vue

- dev-dist/registerSW.js
- src/main.js
- src/sw.js
- vite.config.js
> Small tunes to service worker/pwa

- src/router/index.js
This PR turns on maintenance mode.
No tests needed.
> Turn on maintenance mode

- cypress.config.js
- cypress/e2e/super-admin/default-tests/create-administrations/editAdministration.cy.js
- cypress/support/commands.js
- src/components/CardAdministration.vue
- src/components/ConsentPicker.vue
- src/components/CreateAdministration.vue
- src/components/EditVariantDialog.vue
- src/components/TaskPicker.vue
- src/components/VariantCard.vue
- src/router/index.js
This PR builds functionality for editing the assigned/optional conditions and assent/consent forms for active administrations.
> Fix/Edit Conditions of Administrations

- cypress/e2e/partner-admin/default-tests/testScoreReportFiltering.cy.js
- src/assets/styles/components/datatable.scss
- src/components/RoarDataTable.vue
- src/components/reports/TableScoreTag.vue
- src/helpers/reports.js
- src/main.js
- src/pages/ScoreReport.vue
> WIP: Task Grouping on Score Report

- src/components/CardAdministration.vue
This PR changes the tree tables on the Administration Card to be sorted alphabetically, while also pushing nodes without stats to the end of the list. 
Associated with: https://github.com/yeatmanlab/roar/issues/159
> Sort tree table entries

- src/components/EditUsersForm.vue
- src/components/ListUsers.vue
- src/components/views/LinkAccountsView.vue
- src/components/views/PasswordView.vue
- src/components/views/UserInfoView.vue
- src/pages/AdminProfile.vue
- Make button on password page have a spinner during submission
- Fix spacing on edit user submit/cancel buttons
- Fix styling for chips (PvChip's default stylings seem to be broken- I'm sure this has to do with the changes to CSS going on)
No test needed, CSS tweaks
> Profile Page CSS Tweaks

- src/components/ListUsers.vue
- src/components/RoarDataTable.vue
- src/components/reports/TableScoreTag.vue
- src/helpers/reports.js
- src/pages/ScoreReport.vue
> Fixing ROAM NAN scores

- package-lock.json
- package.json
This PR bumps roar-firekit and roam-fluency
> Bump firekit and ROAM - Fluency

- .github/workflows/cypress-participant-tests.yml
- .github/workflows/cypress-partner-admin-tests.yml
- .github/workflows/firebase-hosting-preview.yml
Allow manual workflow runs for forked repositories. This allows these forked repos to access the repo secrets for CI/CD purposes.
Manual workflow functionality may not be enabled until this PR branch is merged into main with the workflow changes.
> Enh/Allow Manual Workflows

- .github/workflows/cypress-participant-tests.yml
- .github/workflows/cypress-partner-admin-tests.yml
- .github/workflows/firebase-hosting-preview.yml
Specify repository in various workflows, based on whether it was triggered manually or by the pull request.
> Fix/Allow Manual Workflows

- .github/workflows/cypress-participant-tests.yml
- .github/workflows/cypress-partner-admin-tests.yml
- .github/workflows/firebase-hosting-preview.yml
Specifically target the LEVANTE dashboard repo in manual workflows.
> Fix/LEVANTE Manual Workflows

- src/pages/ScoreReport.vue
> Fix - Show Score Tabs

- src/components/tasks/ManageVariants.vue
> Manage Variants duplicate name error checking

- src/pages/HomeParticipant.vue
This PR sorts the assignment dropdown in participant view alphabetically by name. It sorts by name rather than public name so that the partnerships team may include sorting info in the internal name without it showing up in the participant view.
> Sort participant assignment dropdown by name

- package-lock.json
- package.json
- src/pages/RegisterStudents.vue
Allows the CSV Uploader to update or unenroll users.
- [ x I have shared this PR on the roar-pr-reviews channel (if I have access)
> Update CSV Uploader to support edit and unenroll

- src/components/ListUsers.vue
- src/components/auth/AuthEmailLink.vue
- src/components/tasks/TaskCrowding.vue
- src/components/tasks/TaskFluency.vue
- src/components/tasks/TaskLetter.vue
- src/components/tasks/TaskMEP.vue
- src/components/tasks/TaskMultichoice.vue
- src/components/tasks/TaskPA.vue
- src/components/tasks/TaskRan.vue
- src/components/tasks/TaskSRE.vue
- src/components/tasks/TaskSWR.vue
- src/components/tasks/TaskVocab.vue
- src/components/views/UserInfoView.vue
- src/pages/CleverLanding.vue
- src/pages/HomeParticipant.vue
- src/pages/HomeSelector.vue
- src/store/auth.js
> Update calls to users collection to use roarUid

- package-lock.json
- src/components/TaskPicker.vue
> Fix Letra and Palabra no results in task picker search

- cypress/support/commands.js
> fix/Check for Consent/Assent in e2e Tests

- cypress/e2e/participant/default-tests/playVideo.cy.js
- package-lock.json
- package.json
- src/pages/HomeParticipant.vue
- src/pages/HomeSelector.vue
- src/store/auth.js
Please link this PR with the Firekit PR: https://github.com/yeatmanlab/roar-firekit/pull/143
> FIX legal doc popping up

- src/pages/RegisterStudents.vue
`English Language Level` -> `English Language Learner`
- Navigate to CSV Register Users
- Upload any CSV.
- Open a dropdown. You should see an entry with the correct language `English Language Learner`
> Update language on register user dropdown

- cypress/fixtures/generatedTestTemplate.js
- cypress/support/commands.js
> Fix Test Open Admins x2

- cypress/e2e/pre-release-tests/generatePrereleaseTests.cy.js
This should eliminate an error we are encountering in which GitHub actions no longer recognizes the `__dirname` global. 
> Eliminate use of __dirname in pre-release tests

- cypress/e2e/pre-release-tests/generatePrereleaseTests.cy.js
The Vite Cypress preprocessor breaks usage of __dirname. This will update that script to use cypress commands in it's place.
> Update pre-release test generator to not use path variables

- cypress/fixtures/generatedTestTemplate.js
> test admins with no optional assessments

- .github/workflows/cypress-component-tests.yml
- .github/workflows/cypress-participant-tests.yml
- .github/workflows/cypress-partner-admin-tests.yml
- .github/workflows/firebase-hosting-preview.yml
- .github/workflows/firebase-hosting-production.yml
- cypress.config.cjs
- cypress/e2e/participant/default-tests/cleverSignIn.cy.js
- cypress/e2e/pre-release-tests/generatePrereleaseTests.cy.js
- cypress/fixtures/generatedTestTemplate.js
- cypress/support/commands.js
- cypress/support/component.js
- cypress/support/helper-functions/participant/participant-helpers.js
- package-lock.json
- package.json
- src/config/firebaseRoar.js
- src/firebaseInit.js
- src/helpers/query/utils.js
Companion PR: ~~https://github.com/yeatmanlab/roar-firekit/pull/135~~ ~~https://github.com/yeatmanlab/roar-firekit/pull/146~~
Docs PR: https://github.com/yeatmanlab/roar-docs/pull/15
**MAJOR CHANGES**:
- This PR sets up Firebase App Check for use within Firekite and the Dashboard. App Check uses reCAPTCHA tokens to verify that all requests are coming from a list of allowed domains.
- The list of pre-approved domains is `roar.education`, `roar-staging.web.app `for production App Check tokens.
- `localhost` is allowed when developing locally using the debug token, which devs will need in their local `.env` file.
- For PR deploy urls, a new job within the `Build and Deploy` workflow dynamically adds the PR link to the list of approved domains, ensuring that any duplicates are removed. This …
> Add Firebase App Check

- .github/workflows/firebase-hosting-preview.yml
- .github/workflows/firebase-hosting-production.yml
- .github/workflows/firebase-hosting-staging.yml
- package-lock.json
- package.json
- src/config/firebaseRoar.js
This PR removes the debug token injection from PR deployment builds, as Cypress has access to this token from its own environment.
It also updates `roar-firekit `to its latest version, which includes changes to app check initialization.
~~This PR edits the staging/production workflows such that they inject the App Check debug token at build time. This is necessary to do in order for `roar-firekit` to initialize App Check and send a token.~~
~~`roar-firekit `expects a defined `siteKey` and `debugToken` in order to initialize App Check and send debug tokens:~~
~~If both quantities are not defined, a token is not sent and the request fails.~~
> fix/Remove Injection of Debug Token into PR Deploys

- package-lock.json
- package.json
- src/components/CardAdministration.vue
This PR adds a fallback (empty array) value before each of the `forEach` methods in CardAdministration.vue. This resolves an issue where expanded classes were freezing on each administration card.
> Add fallback values before calling the forEach method

- package-lock.json
- package.json
- src/components/ListOrgs.vue
- src/composables/queries/useAdministrationsListQuery.js
- src/composables/queries/useAdministrationsQuery.test.js
- src/composables/queries/useDistrictSchoolsQuery.js
- src/composables/queries/useDistrictsQuery.js
- src/composables/queries/useDsgfOrgQuery.js
- src/composables/queries/useDsgfOrgQuery.test.js
- src/composables/queries/useGroupsQuery.js
- src/composables/queries/useLegalDocsQuery.test.js
- src/composables/queries/useOrgsTableQuery.js
- src/composables/queries/useSchoolClassesQuery.js
- src/composables/queries/useSurveyResponsesQuery.js
- src/composables/queries/useSurveyResponsesQuery.test.js
- src/composables/queries/useTaskVariantsQuery.test.js
- src/composables/queries/useTasksQuery.test.js
- src/composables/queries/useUserAssignmentsQuery.js
- src/composables/queries/useUserAssignmentsQuery.test.js
- src/composables/queries/useUserClaimsQuery.js
- src/composables/queries/useUserClaimsQuery.test.js
- src/composables/queries/useUserDataQuery.js
- src/composables/queries/useUserDataQuery.test.js
- src/composables/queries/useUserStudentDataQuery.js
- src/composables/queries/useUserStudentDataQuery.test.js
- src/helpers/computeQueryOverrides.js
- src/helpers/computeQueryOverrides.test.js
This PR fixes some reactivity issues that were identified across the TanStack query composables. The implemented changes ensure proper reactivity for queries that depend on data from a store or another query. 
To reduce code duplication, this PR introduces a `computeQueryOverrides` which is responsible for: 
- evaluating the `isQueryEnabled` value based on a number of provided conditions
- returning a `queryOptions` object without the original `enabled` property to avoid accidental overriding of the internally computed value 
Additionally, this PR both overhauls existing and introduces new unit tests. Further unit tests will be introduced in subsequent PRs.
n/a
n/a
<br>
Ref yeatmanlab/roar#318
> Fix reactivity in TanStack query composables

- src/components/RoarDataTable.vue
- src/pages/ScoreReport.vue
Update the headings names, and adds a solid white line on the headers to separate student data from tasks
> Fix Score Report Headers

- src/components/auth/SignIn.vue
This PR re-enables the reset password function on the dashboard. I am not sure why this was commented out, however it has been updated and tested. 
> Re-enable the password reset email

- src/pages/ClassLinkLanding.vue
- src/pages/CleverLanding.vue
As discussed with @richford, this PR updates the user type check on the ClassLink landing page to use the `roarUid` instead of `uid`. As this function is identical on both this and the Clever page, a separate PR will be opened to refactor the function into a reusable helper.
n/a
n/a
> Replace `uid` with `roarUid` on ClassLink landing page

- package-lock.json
- package.json
- src/config/firebaseRoar.js
- src/helpers/query/utils.js
This PR updates roar-firekit and comments out anything related to Firebase AppCheck
> Remove Firebase App Check

- src/components/tasks/TaskCrowding.vue
- src/components/tasks/TaskFluency.vue
- src/components/tasks/TaskLetter.vue
- src/components/tasks/TaskLevante.vue
- src/components/tasks/TaskMEP.vue
- src/components/tasks/TaskMultichoice.vue
- src/components/tasks/TaskPA.vue
- src/components/tasks/TaskRan.vue
- src/components/tasks/TaskSRE.vue
- src/components/tasks/TaskSWR.vue
- src/components/tasks/TaskVocab.vue
> Update app launching behavior

- package-lock.json
- package.json
We are currently using version 18 on our dashboard, and for the TROG (syntax) task, the sentences are now showing up, which was not the case with version 16. Since we’re running administrations with the syntax task right now and we don't want the sentences to show up, I’ll be rolling back to version 16 on our end.
> Rolling back Levante core tasks from 18 to 16

- src/pages/ClassLinkLanding.vue
This change hopes to fix the issue of ClassLink teachers being unable to login to the platform. Currently on main, the user is able to login, however on first load (when the user is newly created), they are sent to the participants view. Upon reload they are able to access the admin view, however it is the goal of this PR to make a reload unnecessary.
https://github.com/orgs/yeatmanlab/projects/20/views/1?pane=issue&itemId=83048890&issue=yeatmanlab%7Croar-dashboard%7C871
- Navigate to https://launchpad.classlink.com/cltest
- Contact Elijah to get the login for a test teacher. Login to the launchpad using those credentials
- Make sure the user is deleted (Deleting via the local function is easiest way to do this. if you don't have that set up, Elijah is more than happy to help).
- From the …
> ClassLink user login

- .editorconfig
- .gitignore
- package-lock.json
- package.json
This PR updates the roar-multichoice package to its latest version.
> Update roar-multichoice Packge to 1.11.5

- src/App.vue
Updates the website's user-facing description
> Update the meta description

- package-lock.json
- src/assets/styles/components/tabview.scss
- src/assets/styles/theme-tailwind.css
- src/components/GameTabs.vue
> Fix Game Tabs Being Cut Off on Large Screens

- .github/workflows/firebase-hosting-preview.yml
- src/components/NavBar.vue
- src/translations/en/en-componentTranslations.json
- src/translations/en/us/en-us-componentTranslations.json
- src/translations/es/co/es-co-componentTranslations.json
- src/translations/es/es-componentTranslations.json
> Fix Greeting Translation on Navbar Component

- package-lock.json
- package.json
- src/components/EditVariantDialog.vue
- src/components/GameTabs.vue
- src/components/ListOrgs.vue
- src/components/OrgPicker.vue
- src/components/RoarDataTable.vue
- src/helpers/reports.js
- src/pages/ScoreReport.vue
- src/translations/en/en-componentTranslations.json
- src/translations/en/us/en-us-componentTranslations.json
- src/translations/es/es-componentTranslations.json
> Roar - Inference

- .github/workflows/firebase-hosting-production.yml
- .github/workflows/firebase-hosting-staging.yml
> Use nvmrc for node version in CI

- cypress/e2e/participant/default-tests/checkLegalDoc.cy.js
- src/components/ConsentModal.vue
- src/translations/en/en-componentTranslations.json
- src/translations/en/us/en-us-componentTranslations.json
- src/translations/es/co/es-co-componentTranslations.json
- src/translations/es/es-componentTranslations.json
> simplify assent/consent title

- src/components/ListOrgs.vue
- src/helpers/query/orgs.js
Too many family subgroups showing up in the group tabs. 
> Add toggle to show/hide subgroups

- src/components/GameTabs.vue
This PR resolves an issue with the generated game link URL so that classes and schools are only appended if present.
> Fix the external task launch url to only include classes and schools if present

- .github/workflows/firebase-hosting-preview.yml
The levante-upstream-sync PR originates from the LEVANTE fork. This PR should allow that PR to properly run the standard suite of PR tests.
> Allow fork PRs to run standard PR actions

- src/translations/en/en-componentTranslations.json
- src/translations/en/us/en-us-componentTranslations.json
- src/translations/es/es-componentTranslations.json
On the student dashboard, instead of having Roar - Inference, they should see ROAR - Inference in English and ROAR - Inferencia in Spanish.
NOTE: this is not the last version of Inference, so the game does not need to be played on this PR
> Change Roar - Inference to ROAR - Inference

- package-lock.json
- package.json
- src/helpers/reports.js
> Inference Update

- src/components/ConsentModal.vue
> add reload page to consent modal error msg

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roar-swr` to 1.12.12.
> Update SWR version to 1.12.12

- src/pages/HomeParticipant.vue
- src/pages/HomeSelector.vue
Since it is a new year, the logic for re-signing in August was initially considering August 2025. However, @kellyel and @Emily-ejag updated the logic to check for the most recent August instead of the current year's August.
> Fixing TOS: Update logic for August detection

- src/assets/styles/theme-tailwind.css
- src/components/CardAdministration.vue
- src/components/GameTabs.vue
- src/components/RoarDataTable/RoarDataTable.vue
> CSS minor updates

- src/components/reports/SubscoreTable.vue
- src/components/reports/TableScoreTag.vue
The scores populate fine, but the tags in the progress report change colors when moving back and forward, so created a PR to place the styling in the correct place
> Fix tag css color placement

- src/pages/RegisterFamilyUsers.vue
- src/pages/RegisterStudents.vue
> FIX Pluralize Orgs

- firebase/assessment/firestore.rules
This PR updates the firestore rules for the variants collection. A separate permission is required to allow CollectionGroup queries. Until now, the collection was being accessed exclusively by Super Admins. Now with the Platform Administrator role, a rule was required to allow them access to this collection.
> CollectionGroup Query Rules for /variants/

- src/components/GameTabs.vue
Fixing so that the dashboard automatically bump up to the next incomplete assessment.
> Fix game tabs selection

- src/components/GameTabs.vue
Changing username to PID for external tasks
> External Tasks url param PID

- src/pages/ScoreReport.vue
> Fix: Raw Scores display for Core-Math

- firebase/admin/firestore.indexes.json
Fixing the path for read-aloud since : Firestore index query is failing due to an invalid property path format in collection group queries.
> fixing paths for read-aloud

- vite.config.js
This PR updates the local development environment to use the Firebase development configuration, ensuring that Content Security Policy (CSP) headers are correctly injected into the local Vite server.
n/a
n/a
n/a
> Use dev headers for local environment

- package-lock.json
- package.json
- src/components/ConsentModal.vue
When we updated primevue, some css class names changed. This includes the class that we used to remove the consent modal's reject option. Once this was discovered, we resolved to keep it along with creating a system in which users have their runs and trials marked as 'optOut' for research (see card [here](https://github.com/yeatmanlab/roar-project-management/issues/821). However, until this feature is built out, the no button continues to have no functionality. As the opt out feature is not the current priority, this PR removes the button until the full feature is implemented.
- [ x Any existing end-to-end tests pass with my changes.
> Remove option to reject consent

- .github/actions/deploy/action.yml
- .github/workflows/ci.yml
This PR adds the `repoToken` to the `FirebaseExtended/action-hosting-deploy` action configuration to ensure PR comments containing the ephemeral environment link are posted.
n/a
n/a
n/a
> Add missing token to Firebase deploy action

- .github/workflows/ci.yml
- package-lock.json
- package.json
We needed to update the styling for `roar-inference`
Functionality should remain the same.
Please test `trog`(Syntax) and` roar-inference`
> Update Levante Core Tasks

- .github/workflows/deploy-legacy-staging.yml
- firebase/admin/firebase.staging-legacy.json
This PR temporarily re-introduces deployments to the legacy staging environment.
n/a
n/a
> Temporarily re-introduce deployments to legacy staging environment

- .github/workflows/deploy-development.yml
- .github/workflows/deploy-production.yml
- .github/workflows/deploy-staging.yml
This PR adds the missing `DOTENV_PRIVATE_KEY_{env}` env variables to decrypt `dotenvx` environment configuration injected during the build process. 
n/a
n/a
> Add missing `dotenvx` private keys for deploy steps 

- .github/workflows/deploy-legacy-staging.yml
> Fix private key env var name for legacy staging deployments 

- firebase/admin/firestore.indexes.json
These indexes are required for the queries that are needed to retrieve an external participant's assignments (e.g. task launching)
> update firestore indexes for external assignment query

- src/components/ListOrgs.vue
- src/store/auth.js
Only super admins should be allowed to see the invite codes column. 
> only allow superadmins to view invite code

- firebase/admin/firestore.indexes.json
This addresses the inconsistent index behavior that was happening with the external student launcher. 
> Update assignment indexes to include `Collection` 

- src/helpers/query/assignments.js
This PR fixes a bug in which students are seeing closed administrations in participant home view.
> FIX: Restrict user assignments to open assignments

- src/helpers/query/assignments.js
- src/pages/ScoreReport.vue
Reintroduction of the previous PR to correct the date checking for launching students
> FIX: Only show the launch student button for open administrations

- firebase/admin/firestore.indexes.json
Updates firestore indices to add the `dateClosed` attribute. This update is in response to the changes that we'd made to the  `administrationFetcher` to only retrieve open administrations. This PR should resolve the 400 errors that Adam had been seeing upon testing the task launching features as well as the failing `launchExternalStudent` cypress tests. 
> update firestore.indexes to add dateClosed fieldPath

- firebase/admin/firestore.indexes.json
This pull request updates the `firestore.indexes.json` file to properly deploy the compound indexes for `assignments` that are used in the external task launcher. 
> update indexes for dateClosed to proper place

- src/components/GameTabs.vue
This pull request addresses: [#850](https://github.com/yeatmanlab/roar-project-management/issues/850)
> Only show SWR Video tutorial to grades at or below 3rd

- package-lock.json
- package.json
Bumps firekit version to 9.6.2. This version includes new permissions that are utilized by the new CSV Uploader.
> Bump firekit verison

- cypress/support/query.js
This pull request enhances the Cypress super admin test `deleteTestRuns` to also delete all trials associated with a user's runs collection.
> enh/Delete Test Runs and Trials as Cypress Super Admin

- src/pages/ProgressReport.vue
Adds launch button to the progress report data table as it is in the score report table. 
> Add launch button to progress report

- src/components/ListUsers.vue
- src/pages/ScoreReport.vue
Includes the `state_id` attribute in the listOrgs and ScoreReport datatables to allow Clever authenticated schools to use this identifier to match scores with students. 
> update score datatable and listorg datatable to display stateId

- src/components/tasks/ManageTasks.vue
- src/components/tasks/ManageVariants.vue
- src/containers/ManageTasks/components/CreateTaskForm.vue
- src/containers/ManageTasks/components/UpdateTaskForm.vue
These permissions were not updated when the permissionGroup `Tasks` was updated.
> Update outdated task permissions

- src/components/GameTabs.vue
This PR allows any external taskId that contains `"qualtrics"` to pass participantId as URL param
> Qualtrics External Tasks Participant ID URL param

- package-lock.json
- package.json
Reverts yeatmanlab/roar-dashboard#1174
> Revert "Update PA version to 3.0.0"

- package-lock.json
- package.json
> Letter go back to 2.1.0

- .github/workflows/deploy-production.yml
This PR implements the following changes to the production deployment workflow: 
- Product owner review: Before a production workflow can begin, moving forward, product owners will need to approve the workflow run. 
- Engineering review: Once a product owner has given their approval, only a single approval will be required from engineering as the app and Firestore config deployment steps have been consolidated into a single step. 
n/a
n/a
> Add product owner review step to production release workflow

- src/components/tasks/TaskLetter.vue
- src/components/tasks/TaskMultichoice.vue
- src/components/tasks/TaskPA.vue
- src/components/tasks/TaskRan.vue
- src/components/tasks/TaskReadAloud.vue
- src/components/tasks/TaskSRE.vue
- src/components/tasks/TaskSWR.vue
- src/components/tasks/TaskVocab.vue
- src/containers/Navigation/Navigation.vue
- src/pages/HomeSelector.vue
- src/router/sidebarActions.js
This PR adds logic to return to the `LaunchParticipant` component after task completion if the task was externally launched. The current behavior routes to the parent's home, which is inconvenient if an externally launched participant wishes to take multiple assessments. 
This PR also fixes a bug where the parent was not being shown the consent form
In addition, this PR removes the navbar items from parent view
> Return to participant home after task completion for externally launched assessments

- cypress.config.cjs
- cypress/e2e/super-admin/clean-up/deleteTestRuns.cy.js
- cypress/support/query.js
- package-lock.json
- **update env configs**
- **rewrite super admin tests for deleting test runs and assignments**
- **remove UnHeadVite from cypress config**
- **refresh node modules and package-lock**
This PR allows the Cypress super admin account to programmatically delete runs and trials from Cypress test studnets on the client side.
> Delete Test Runs and Trials as Cypress Super Admin

- src/pages/HomeParent.vue
This PR reverts a change that was bundled in with a dashboard release commit. The change added a `.value` to the `initialized` ref being passed into the administration assignment queries which invalidated logic used to determine whether the query was enabled. 
I've tested locally that this fix addresses the behavior where the student cards would not populate due to no assignments being returned by the query. 
> Fix Adminstration Assignment queries for ParentView

- src/pages/HomeParent.vue
Adds a hot fix that was seemingly removed
> update to remove .value again

- package.json
This PR changes the `npm version` script to use `npm run format:check` instead of `npm run format` before incrementing the version number. It should block versioning if `format:check` fails rather than introducing unknown formatting changes before versioning.
> [Maint]: Use format:check instead of format before versioning

- package-lock.json
- src/components/tasks/TaskReadAloud.vue
- src/components/tasks/TaskSWR.vue
- src/containers/Navigation/Navigation.vue
- src/helpers/reports.js
- src/router/index.js
Adds support for ROAR-Readaloud to be launched externally. Also adds the `roar-readaloud` entry in` taskDisplayNames` to fix bug where the task name wasn't showing up. I'd seen the taskId returned as both `roar-readaloud` and `roar_readaloud`, so the changes include both keys in the dictionary. This inconsistency of taskId may be a bug and should be addressed in the future.
> Add ROAR-Readaloud as a launchable game and add task data to `taskDisplayNames`

- src/router/index.js
We need the phonics route to be able to render the game component for external launches. 
> Add phonics as launchable task

- src/components/tasks/TaskCrowding.vue
- src/components/tasks/TaskLetter.vue
- src/components/tasks/TaskLevante.vue
- src/components/tasks/TaskMEP.vue
- src/components/tasks/TaskMultichoice.vue
- src/components/tasks/TaskPA.vue
- src/components/tasks/TaskRan.vue
- src/components/tasks/TaskReadAloud.vue
- src/components/tasks/TaskRoam.vue
- src/components/tasks/TaskSRE.vue
- src/components/tasks/TaskSWR.vue
- src/components/tasks/TaskVocab.vue
We want to make sure that our `setInterval` methods are cleared when a component is unmounted to prevent a memory leak. 
> Add clearInterval to prevent memory leak in setInterval instantiations

- src/components/GameTabs.vue
- src/composables/queries/useAdministrationAssignmentsQuery.js
- src/translations/en/en-componentTranslations.json
- src/translations/en/us/en-us-componentTranslations.json
- src/translations/es/co/es-co-componentTranslations.json
- src/translations/es/es-componentTranslations.json
Adds components to check `unsuitableForScoring` attribute to allow participants to retake assessments. 
> Add component to allow retake of unsuitableForScoring assessments

- src/components/StudentCard.vue
- src/pages/HomeParticipant.vue
The issue was that `immediate: true` was not set in the org intersection watch function and that the enabling boolean was being tripped based off of the parent object being set and not the child `orgType` and `orgId` objects that were being passed into the query. Now the participant's assignments load on the initial render using the router-link. 
> [FIX] Fix bug where `<router-link>` component would not allow student view to render correctly on initial render

- src/components/ConsentPicker.vue
- src/components/CreateAdministration.vue
This PR rectifies a few issues I noticed.
- Give proper error message when org selection is invalid
- Properly assign tasks and orgs on first load
- Make consent picker correctly display status of consent on first load
> [FIX] Small issues on Edit/Duplicate admin form

- src/containers/Navigation/Navigation.vue
The entry for the launched fluency-arf task was malformed in the `NavbarBlacklist` list, meaning that the navbar was erroneously showing when the task would load. 
> Remove extra space for fluency-arf in navbar blacklist

- .eslintrc.json
- .gitmodules
- .prettierignore
This PR removes the roar-firebase-functions submodule from the dashboard repo. This is cruft left over from a time when we thought it would be necessary to incorporate the firebase functions for firebase emulation. We don't do this currently and any plans to do so have been made obsolete by the upcoming backend refactor.
> Remove roar-firebase-functions submodule

- cypress.config.cjs
- cypress/e2e/parent/default-tests/addChild.spec.cy.js
- cypress/e2e/parent/default-tests/auth.cy.js
- cypress/support/commands.js
- src/components/HomeParentStudentView.vue
- src/components/StudentCard.vue
- src/pages/HomeParent.vue
This PR introduces minor improvements to the `addChild` E2E specs which is currently failing on a regular basis. As discussed, these changes are no proper fixes and only aim to temporarily improve the stability of these tests slightly.
> Improve parent child addition E2E tests 

- src/components/HomeParentStudentView.vue
This allows the `addChild` cypress test to be reset without having to re-initialize the `childrenUids` array with a dummy UID
> Update parent student view to allow parents to add students in the zero condition

- apps/dashboard/src/components/GameTabs.vue
- apps/dashboard/src/constants/levanteTasks.js
- apps/dashboard/src/constants/tasksExcludedFromRetake.js
- package-lock.json
This pull requests disables the functionality for retaking assessments if that taskId of that assessment is a LEVANTE task other tasks listed in `excludeFromRetake` array.
This is because these apps do not handle reliability i.e. they lack the ability to change the  `reliable` flag from `false` to `true`. The result of this is that these assessments always trigger the retake assessment functionality, even if the user's run is otherwise reliable and valid.
> `fix` Exclude Core Tasks From Assessment Retake Functionality

- apps/dashboard/package.json
- package-lock.json
Roar-survey now writes to production. 
> Bump roar-survey

- .gitmodules
This PR updates the git submodule configuration to use a relative path instead of an absolute GitHub URL for the roar-dashboard-envs submodule. This improves flexibility because relative paths work regardless of whether the repository is accessed via HTTPS, SSH, or other protocols. Developers can clone and work with the repository using their preferred Git protocol without submodule URL conflicts.
> Use relative path for git submodules

- apps/dashboard/src/components/HomeParentStudentView.vue
Addresses https://github.com/yeatmanlab/roar-project-management/issues/1141
> Update language for parent zero condition

- apps/dashboard/cypress/e2e/parent/default-tests/addChild.spec.cy.js
- apps/dashboard/cypress/e2e/parent/default-tests/auth.cy.js
- apps/dashboard/cypress/e2e/participant/default-tests/assessments/assessments.cy.js
- apps/dashboard/cypress/e2e/participant/default-tests/legal.cy.js
- apps/dashboard/cypress/e2e/partner-admin/default-tests/progressReports.cy.js
- apps/dashboard/cypress/e2e/partner-admin/default-tests/scoreReports.cy.js
- apps/dashboard/cypress/e2e/super-admin/default-tests/create-administrations/createAdministration.spec.cy.js
- apps/dashboard/cypress/e2e/super-admin/default-tests/create-administrations/editAdministration.cy.js
- apps/dashboard/cypress/e2e/super-admin/default-tests/listOrgs.spec.cy.js
- apps/dashboard/cypress/e2e/super-admin/default-tests/register-students/registerStudents.spec.cy.js
- apps/dashboard/src/components/ConsentModal.vue
- apps/dashboard/src/components/Form/DateInput/DateInput.vue
- apps/dashboard/src/components/Form/Dropdown/Dropdown.cy.js
- apps/dashboard/src/components/Form/Dropdown/Dropdown.vue
- apps/dashboard/src/components/GameTabs.vue
- apps/dashboard/src/components/HomeParentStudentView.vue
- apps/dashboard/src/components/ListOrgs.vue
- apps/dashboard/src/components/NavBar/NavBar.cy.js
- apps/dashboard/src/components/NavBar/NavBar.vue
- apps/dashboard/src/components/RoarDataTable/RoarDataTable.cy.js
- apps/dashboard/src/components/RoarDataTable/RoarDataTable.vue
- apps/dashboard/src/components/auth/RegisterChildren.vue
- apps/dashboard/src/components/auth/RegisterParent.vue
- apps/dashboard/src/components/modals/EditVariantDialog.vue
- apps/dashboard/src/components/reports/TableScoreTag.vue
- apps/dashboard/src/pages/RegisterStudents.vue
This PR replaces PrimeVue classes (prefxied with `.p-`) with`data-testid` using passthrough properties for Cypress tests.
Resolves https://github.com/yeatmanlab/roar-project-management/issues/319
> Replace PrimeVue class selectors with testIds

- apps/dashboard/cypress.config.cjs
- apps/dashboard/cypress/e2e/partner-admin/default-tests/longitudinalChart.cy.js
Adds testing for longitudinal reports. 
> Add Longitudinal Chart Test

- apps/dashboard/package.json
- package-lock.json
> Bump survey to 0.2.2

- apps/dashboard/src/components/auth/RegisterParent.vue
Language change for the checkbox as requested by @jyeatman in https://github.com/yeatmanlab/roar-dashboard/pull/1335#issuecomment-3325398657
> Change text for `Contact me about....` checkbox

- apps/dashboard/src/containers/StudentScoreReport/components/ScoreCard.vue
- apps/dashboard/src/containers/StudentScoreReport/components/ScoreCardsListSection.vue
- apps/dashboard/src/pages/ScoreReport.vue
- apps/dashboard/src/services/ScoreReport.service.js
- apps/dashboard/src/translations/en/en-individualScoreReport.json
- apps/dashboard/src/translations/es/es-individualScoreReport.json
- apps/dashboard/vite.config.js
This PR adds phonics subscores to the new individual score report. 
> Add subscores for individual score report

- apps/dashboard/src/components/auth/RegisterParent.vue
- apps/dashboard/src/components/reports/TableScoreTag.vue
- apps/dashboard/src/pages/ScoreReport.vue
- apps/dashboard/src/router/index.js
This PR updates tooltips & exported values for sre-es to better align with sre, while maintaining compatibility with previous sre-es scores, including admins with students with both normed & unnormed scores. 
https://github.com/user-attachments/assets/8b893600-db6f-4cb9-b001-83567c770d72
https://github.com/user-attachments/assets/bfb09664-13f3-4c20-b340-02696ea3c7e8
> Update sre-es score report & fix task launcher

- apps/dashboard/src/components/reports/IndividualScoreReportTask.vue
- apps/dashboard/src/components/reports/tasks/TaskReport.vue
- apps/dashboard/src/helpers/reports.js
- apps/dashboard/src/helpers/reports.test.js
- apps/dashboard/src/pages/ScoreReport.vue
- apps/dashboard/src/pages/StudentReport.vue
This PR updates the thresholds for Word, Sentence, Palabra, and Frase. 
See https://github.com/orgs/yeatmanlab/projects/151/views/1?pane=issue&itemId=130950376&issue=yeatmanlab%7Croar-dashboard%7C1372 for values. 
https://github.com/user-attachments/assets/5a71c549-f43c-4337-b399-73d681a37e05
> Update score report thresholds 

- apps/dashboard/src/pages/ScoreReport.vue
Changes 
- Fix Frase standardScore
> Address swr & sre QA feedback 

- apps/dashboard/src/helpers/reports.js
- apps/dashboard/src/pages/ScoreReport.vue
This PR fixes the error where the percentile was being displayed as the standard score and updates the score reports to display/export the new support level for normed scores. 
> Fix standardScore and add supportLevel for Frase

- apps/dashboard/src/pages/HomeParticipant.vue
This PR fixes two bugs:
- Current administration wasn't shown in the dropdown when redirected or navigating back from a game.
- User with multiple admins requiring consent wouldn't see other consent modals after confirming for one admin in the same login session. 
https://github.com/user-attachments/assets/09938b7a-1cd3-4915-b3a7-4ce058e2a400
https://github.com/user-attachments/assets/277aed61-62b9-4fd9-9779-6d3500a2811c
- ## Types of changes
> Fix missing dropdown admin and consent forms for multiple admins

- apps/dashboard/src/pages/ScoreReport.vue
https://github.com/user-attachments/assets/f3805fc2-18ce-4c90-9812-15e5b2a177f2
> Use scoringVersion from variant instead of scores for Frase exported data 

- .github/actions/deploy/action.yml
This PR fixes the Firetore config deployment by removing the build artifact deletion step from the deploy action. This fix is to be considered a band-aid solution until the CI/CD workflows are refactored for the upcoming backend integration.
> Fix Firestore config deployment
