yeatmanlab/roar-dashboard

- package-lock.json
- package.json
- src/components/ConsentModal.vue
- src/main.js
- src/pages/Home.vue
- src/pages/MassUploader.vue
- src/pages/Participant.vue
- src/store/auth.js
This PR adds consent functionality to the dashboard.
- On login, check if the user has already consented to this version of the consent (updates are based on gitHub commit hashes)
- If not, determine type of consent document based on admin or student account. 
- Show the user that consent doc, and do not allow them to proceed until they have accepted. 
- After accepting, update their userdoc to reflect accepted consent (with timestamp)
Requires RoarFirekit [PR #45](https://github.com/yeatmanlab/roar-firekit/pull/45)
> Consent Component

- src/components/CreateAdministration.vue
- src/components/CreateAdministrator.vue
- src/components/CreateOrgs.vue
- src/components/ListOrgs.vue
- src/components/ListUsers.vue
- src/pages/AdministrationProgress.vue
- src/pages/Administrator.vue
I believe the issue here is that we were relying on the `$subscribe` method solely. `$subscribe` is fantastic for waiting for changes to firekit to trigger the refresh function. However this fails when firekit is already initialized, such as navigating to a page well after the user has logged in. 
This PR adds a simple check to `onMounted()`, where we check whether firekit is ready. If so, we want to call refresh and start gathering data. If not, simply do nothing and wait for `$subscribe` to take care of it.
> Fix refresh bug

- src/store/auth.js
This PR fixes grabbing the admin data from the participant view. This error manifested in a breakdown of the sequential logic, which relies on the field grabbed from this call
> Correctly grab administration info in authStore

- src/components/CreateOrgs.vue
- src/components/ListUsers.vue
- src/pages/Administrator.vue
- src/pages/RegisterStudents.vue
- src/router/index.js
- src/router/sidebarActions.js
This implements various fixes, enhancements and requests. 
- Adds superAdmin route guard to register students
- Adds register student restriction to require district and school, or group.
- Adds partial reset functionality to create orgs form (instead of routing)
- Once admin landing page loads, display 'no admins' rather than inf spinner.
**ALSO**: I've added some logic to both the admins list and users list for catching a 'FirebaseError: missing or insufficient permissions' when there are no docs to display. I'm not sure if this is the error that is returned when there are no documents to display (which is the case here) OR if there's a permissions issue. May be related to https://app.clickup.com/t/8685e5wrz
> Admin Enhancements

- src/store/auth.js
This PR prevents admin users from switching to participant view on reload. 
I think this was introduced very recently, but as far as I can tell, this shows up because the roarfirekit function returns 'false' if you call it fast enough (I believe on reload, the Home.vue page calls it immediately after initialization, but before the user idTokens are grabbed). 
So this PR implements a studier cache of the admin and superAdmin traits.
> Keep admin status on page reload

- src/config/firebase.js
This PR changes the auth domain as described here:
https://cloud.google.com/identity-platform/docs/show-custom-domain
I’m changing this because Carrie wasn’t able to log in without allowing third-party cookies. The third-party cookies are required when the auth domain is different from roar.education. See these pages for details and examples:
- https://stackoverflow.com/a/48816737
- https://dev.to/killdozerx2/fixing-3rd-party-cookies-issue-with-firebase-auth-28ng
> Update auth domain to avoid third-party cookie requirements

- package-lock.json
- package.json
- src/components/ParticipantSidebar.vue
- src/pages/CleverLanding.vue
- src/pages/Home.vue
- src/pages/Participant.vue
- src/store/game.js
This PR changes the logic of participant view to cope with multiple administrations being assigned to the user. The dropdown appears when more than one administration is detected, and allows the user to swap between the admins at will. 
You can test a user with multiple admins using `labtest1` and `password1`. To test a user with just one admin, use any clever student assigned to the BRSSD admin via clever. 
I tried to test this in most scenarios but I would appreciate if you tested this one a bit more rigorously as essentially every user will be touching this functionality.
> Handle Multiple Admins on Participant

- src/App.vue
- src/router/index.js
Resolves https://github.com/yeatmanlab/roar/issues/45
@kellyel, can you take a look to make sure this doesn't have any unintended consequences. I tested with username/password students and some Clever users (make sure to test with Demo district users because we have live Clever users now.
For the above linked issue, I was able to reproduce on Chrome but not Brave. Logging out and then trying to log in **as another user** did not work. Same user was okay. With this change, it forces a replacement of the `<router-view>` element/component every time a navigation event occurs. See https://dev.to/brylie/reload-router-view-when-vue-route-changes-3cck
> Add a key to router view

- src/pages/RegisterStudents.vue
Minor mismatch in variable names causing names to not get saved to firebase. Corrects https://github.com/yeatmanlab/roar/issues/57 and https://github.com/yeatmanlab/roar/issues/56
> Correct names not getting saved to firebase

- src/components/tasks/Letter.vue
- src/components/tasks/Multichoice.vue
- src/components/tasks/PA.vue
- src/components/tasks/SRE.vue
- src/components/tasks/SWR-ES.vue
- src/components/tasks/SWR.vue
This PR resolves a bug in which games with keyboard responses (e.g., SWR, SWR-ES, SRE) are unable to progress past the first keyboard response screen under the following conditions:
- A game from the above list has been previously completed
- The page has not been refreshed
When these conditions were satisfied, the keyboard listeners that are normally active are no longer there.
Here is a screenshot of what it looks like when it's working:
And here's what it looks like when it fails (no `keyup` or `keydown` listeners):
Since the failure did not reproduce on page reload, this PR provides a somewhat hacky solution: simply reloading the page after the task is complete.
> Fix the game completion replay bug

- src/components/auth/AuthEmailLink.vue
This PR mitigates the failure of email-link sign in. I tried to replicate this issue on my localhost and could only get it to reproduce perhaps 10% of the time. This PR does not actually fix the issue but rather tries to mitigate the failure mod by setting a timer and redirecting to sign-in if the auth workflow is taking too long. This reuses the pre-existing error message.
This isn't an ideal solution but is a good enough bandaid for now.
> Reroute to sign-in if email-link auth is taking too long

- src/helpers/index.js
The flatten function was checking truthy-ness when setting values. I have changed this to allow zeros as well. This results in the table exporting zeros along with every other truthy value, while still replacing non-zero falsey values.
> Account for zeros in flatten function

- src/App.vue
- src/router/index.js
This PR creates a new route in index.js for tasks that have the taskId=morphology rather than the generic taskId=multichoice. This ensures that games with either taskId will run correctly in the dashboard.
> New Route for Morphology Tasks.

- src/components/reports/SubscoreTable.vue
For the letter subscore table, I used `_toUpper` to sort the table, but `_toLower` to sort the data on export. This PR standardizes those operations
> Standardize sorting for table & export functions

- src/pages/AdministrationProgress.vue
When a partner admin navigates to the progress report page and exports a selected progress report, the file saves as `roar-scores-selected.csv`. This PR changes the naming convention to `roar-progress-selected.csv`.
> fix progress report file naming

- src/components/GameTabs.vue
Corrects an issue where RockRest students are able to play games after the task has already been completed
> Lock assigments after the task is completed

- src/components/RoarDataTable.vue
- src/components/reports/SubscoreTable.vue
- src/pages/ScoreReport.vue
This pull request adds tooltips to the score report. Tooltips are now included in:
- export selected/export whole files
- data table columns for tasks (sentence, phoneme, etc)
- student score swatches
Tool tips are currently implemented for Phoneme, Word, Sentence, Letter, and Palabra tasks.
This PR also includes some small stylistic changes to the score report requested by the partnership team.
> Add report tooltips

- package-lock.json
- src/helpers/query/tasks.js
In the new getVariants query, we were missing the taskId inside the task object needed to create admins.
> Fix administration creation

- src/helpers/query/assignments.js
- src/helpers/query/runs.js
- src/helpers/query/utils.js
- src/pages/HomeParticipant.vue
- src/pages/ScoreReport.vue
- src/store/scores.js
Many of the batchGet requests had duplicated entries. This PR first uses `_uniq` to reduce the size of the batchGet document lists (sometime reducing to a third of the original size). This also required some downstream changes to the fetchers since the batchGet document array were no longer the same length as the arrays for assessments/runs/scores. Practically, this meant using `_find` instead of `_zip`.
This PR is based on top of #248
> Optimize REST batchGet queries

- package-lock.json
- src/pages/ScoreReport.vue
This PR changes Score Reports so that the new graphs are a feature for super admins only. The graphs above the table are hidden, and the graphs below the table are replaced with the old text when a non-super admin views the report.
> Make distribution graphs super-admin only again

- src/components/reports/tasks/TaskReport.vue
- src/helpers/reports.js
- src/pages/ScoreReport.vue
Fixes behavior where graphs of unsupported tasks like ROAR letter would show up empty.
> Only display graphs for SRE, SWR, and PA

- src/components/CardAdministration.vue
This PR removes the buggy spaces that were getting rendered after each task ID by wrapping the taskID variable directly in a span. It also updates the task names to match the public display names. (cva -> Written Vocabulary and morphology -> Morphology)
From https://app.clickup.com/t/86873882e
> Remove spaces after assessment Ids and update task names 

- src/components/CardAdministration.vue
This PR removes the declared `displayNames` object in `cardAdministration.vue` to instead utilize the central `taskDisplayNames` object declared in `helpers/reports`
> Remove locally declared displayName for util imported taskDisplayNames

- src/components/RoarDataTable.vue
- src/components/reports/DistributionChartOverview.vue
- src/components/reports/DistributionChartSupport.vue
- src/helpers/query/assignments.js
- src/helpers/reports.js
- src/pages/ScoreReport.vue
Changes filter dropdowns to `Green`, `Yellow`, and `Pink`
Changes all references to support levels on the score reports to `Needs Extra Support`, `Developing Skill`, and `Achieved Skill`
> Update language for support levels

- src/components/RoarDataTable.vue
- src/helpers/query/assignments.js
This fixes intermittent query failures due to missed scores. This solution should allow ALL users (superadmin, partner admins) to perform filter queries.
> Fix some query failures

- package-lock.json
- src/components/RoarDataTable.vue
- src/helpers/reports.js
- src/pages/ScoreReport.vue
This PR changes the way we handle control over how individual tasks are displayed in the score reports. Rather than having a blacklist, `excludedTasks`, we want to have a whitelist of fully scored tasks and a whitelist of raw-only tasks. All other tasks will still display, just with an outlined circle with tooltip 'These scores are under development'.
> Implement whitelist of fully scored tasks

- src/pages/ScoreReport.vue
I believe one of the student's grade attributes may have been a number, causing the `grade.toLowerCase()` call to fail.
> Fix parse grade bug

- cypress/e2e/participant/default-tests/playPA.cy.js
- cypress/e2e/participant/default-tests/playSRE.cy.js
- cypress/e2e/participant/default-tests/playSWR.cy.js
- cypress/e2e/participant/network-tests/roar-swr/playSWR-2G.cy.js
- cypress/e2e/participant/network-tests/roar-swr/playSWR-3G.cy.js
- cypress/e2e/participant/network-tests/roar-swr/playSWR-HighLatency.cy.js
- cypress/fixtures/buttonGamesList.js
- cypress/support/helperFunctions/roar-swr/swrHelpers.js
Task names are now updated in firebase with the `ROAR-{taskName}` schema, so the tests must be updated as such.
> Update Cypress Tests for Standardized Names

- src/components/RoarDataTable.vue
- src/helpers/query/assignments.js
- src/pages/ProgressReport.vue
- src/pages/ScoreReport.vue
This PR adds sorting and filtering to the progress report. The current iteration supports sorting and filtering on most categories in the table, as well as sorting by grade and school.
One caveat is that filtering by completion status is currently limited to only `Completed` and `Started`. This is because the filtering mechanism is built on the scores collection, where non-completed and non-started assignments will have no entry. I tried to implement the filtering mechanism based on the assessments collection, but ran into some road blocks (at least from what I tried) in being unable to query within the nested array `assignments`. You can see the prototype code [here](https://github.com/yeatmanlab/roar-dashboard/pull/386/commits/5e76647b7b3ca707d61ffff2e916513f9b9d5223).
> Add Filter and Sorting for Progress Reports

- package-lock.json
- package.json
- src/firebaseInit.js
This PR turns on verbose Firekit output, for the purpose of debugging. This will be undone in production once we have solved an issue.
> Enable Verbose Firekit

- .github/workflows/deploy-firebase-test-cypress.yml
- cypress.config.js
- cypress/e2e/participant/default-tests/loginAndLogout.cy.js
- cypress/support/commands.js
- src/assets/styles/components/_defaults.scss
- src/components/auth/SignIn.vue
- src/pages/SignIn.vue
- src/translations/en/en-componentTranslations.json
- src/translations/en/us/en-us-componentTranslations.json
- src/translations/es/co/es-co-componentTranslations.json
- src/translations/es/es-componentTranslations.json
This PR adds the ability to log in using a password for email users.
> Allow Email login

- cypress.config.js
- cypress/e2e/participant/default-tests/es-tests/playFluency-ARF-ES.cy.js
- cypress/e2e/participant/default-tests/es-tests/playFluency-CALF-ES.cy.js
- cypress/e2e/participant/default-tests/es-tests/playLetter-ES.cy.js
- cypress/e2e/participant/default-tests/es-tests/playSentence-ES.cy.js
- cypress/e2e/participant/default-tests/es-tests/playWord-ES.cy.js
- cypress/e2e/participant/default-tests/playOptionalGames.cy.js
- cypress/e2e/participant/default-tests/playSRE.cy.js
- cypress/e2e/participant/default-tests/playSWR.cy.js
- cypress/support/helper-functions/roar-letter/languageOptions.js
- cypress/support/helper-functions/roar-letter/letterHelpers.js
- cypress/support/helper-functions/roar-sre/languageOptions.js
- cypress/support/helper-functions/roar-sre/sreHelpers.js
- cypress/support/helper-functions/roar-swr/languageOptions.js
- cypress/support/helper-functions/roar-swr/swrHelpers.js
This PR builds out support for parameterizing app tests based on language, including spanish variants.
> Cypress Tests for Multilingual Apps

- src/components/RoarDataTable.vue
- src/helpers/reports.js
from single letter recognition to letter names and sounds
> Change ROAR-Letter name

- src/pages/RegisterStudents.vue
This PR
1. Updates delay between student creation chunks
2. Adds 'Test Data' column to tag individual users as test data. Accepts anything JavaScript considers truthy. To ignore a row, keep the call empty or set to `null`, `undefined`, `0`, `false`
> Students test data flag

- src/components/tasks/RegisterTask.vue
This PR adds a checkbox control to appending the variant url to the variant parameters when registering a new game variant through the dashboard.
> Optional Variant URL in Firestore

- cypress/e2e/participant/default-tests/playPA.cy.js
- cypress/support/helper-functions/roar-pa/paHelpers.js
- package-lock.json
- package.json
temporary solution for storyOption and story + Internationalization
> PA Story Option Update

- cypress/e2e/partner-admin/default-tests/viewIndividualReport.cy.js
- src/components/reports/IndividualScoreReportTask.vue
- src/pages/IndividualReport.vue
as per https://github.com/yeatmanlab/roar/issues/246
> update individual score reports

- src/components/ConsentModal.vue
I found a neat un-documented prop to prevent the esc event from closing the modal.
> Prevent ESC closing consent modal

- package-lock.json
- package.json
- src/components/CreateAdministration.vue
- src/components/EditVariantDialog.vue
- src/components/OrgPicker.vue
- src/components/TaskPicker.vue
- src/components/VariantCard.vue
This PR fixes an issue with the edit administration form to better match with existing variants. Previously, the form would remove null values from the params in `allVariants` before comparing to the parameters of the administration. But sometimes the administration parameters contained those null values. This PR removes the null values from both before comparing.
> Remove nulls from both sets of params before comparing

- firebase/admin/firestore.indexes.json
I noticed that the admin indexes were failing to update on the last few dashboard deployments. This PR updates the indexes to reflect what we have online
> Update Firestore indexes

- src/components/CardAdministration.vue
- src/components/CreateAdministration.vue
this pr adds the variant id and variant name, and if the admin has it, then it shows on view params
> Adding VariantId and VariantName

- src/components/CreateAdministration.vue
This PR sets the parameter for 'registered' to 'true' in variantsFetcher(), so that only variants with boolean value 'registered' set to 'true' will be fetched when creating an administration.
> Only Fetch Registered Variants

- package-lock.json
- package.json
- src/components/CreateOrgs.vue
- Disable submit button when creating org
- Disable button if vuelidate model is invalid -- any _required_ fields are missing / invalid
Context / Reason: It's a bad and annoying experience as a user to fill out a form, submit it, and only then know what is required. Instead, from the get go they should know what fields they need to fill in. Additional changes should be made in the future to add red asterisks to the required fields, making it abundantly clear.
> Changing org form feedback when submitting

- .github/PULL_REQUEST_TEMPLATE.md
This PR adds a PR template that will serve as a starting point for all future PRs. It is intended to be a general purpose PR template for use in **ALL** ROAR repositories. If it is approved and merged for this repository, I will then add it to all other ROAR repos.
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
This PR does not warrant adding any tests.
> ENH: Add PR template

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roar-sre` to 1.15.9.
> Update SRE version to 1.15.9

- src/components/reports/TableScoreTag.vue
- src/helpers/reports.js
- src/pages/ScoreReport.vue
For PA, SWR, SRE and their Spanish counterparts.
> Filter EngagementFlags in Score Report based on IncludedValidityFlags

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roav-ran` to 1.0.18.
> Update ROAV-Ran version to 1.0.18

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roav-crowding` to 1.1.11.
> Update ROAV-Crowding version to 1.1.11

- src/pages/HomeParticipant.vue
When switching admins on Home participant the consent/assent wasn't immediately loading, unless you refresh the page. This PR fixes this issue.
> Ensuring the new consent appears when switching the administrations on participant view

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roav-ran` to 1.0.19.
> Update ROAV-Ran version to 1.0.19

- src/assets/styles/theme.css
- src/components/RoarDataTable.vue
- src/pages/ProgressReport.vue
- src/pages/ScoreReport.vue
On the Score Report move "Word, Sentence, and Phoneme" first, then gray out cell that belong to the other task because those are not validated.
On Progress Report only move the validated tasks first.
> Move core assessments and visually separate tasks in score report

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roam-fluency` to 1.11.24.
> Update ROAM-Fluency version to 1.11.24

- cypress/e2e/participant/default-tests/checkLegalDoc.cy.js
- src/components/ConsentPicker.vue
- src/components/CreateAdministration.vue
- src/components/OrgPicker.vue
- src/components/TaskPicker.vue
- src/pages/HomeParticipant.vue
Implement watchers and invalidate queries in order to properly handle administration edits.
Firekit PR: https://github.com/yeatmanlab/roar-firekit/pull/140
> fix/Edit Administrations

- cypress.config.cjs
- cypress/e2e/participant/default-tests/checkLegalDoc.cy.js
- src/pages/HomeParticipant.vue
> Force legal doc sign reset Aug 1st

- cypress/e2e/participant/default-tests/playOptionalGames.cy.js
- cypress/support/commands.js
- src/pages/HomeParticipant.vue
- src/store/auth.js
This PR stores the state of "show optional assessments" within the auth store. This allows users to persist this state between assessments.
> Store State of Show Optional Assessments

- src/pages/HomeSelector.vue
Fix an issue where terms of service status was being checked before userData was loaded, which caused the TOS modal to always appear even if TOS was previously signed.
> fix/Terms of Service Popup

- src/components/RoarDataTable.vue
- src/pages/ProgressReport.vue
- src/pages/ScoreReport.vue
Update the format of the default sort to make it functional on score and progress reports.
- Navigate to score report
- After table loads, there should already be a sort applied - school (1), grade (2), and last name (3)
- Navigate to a progress report
- Should see the same default sort without any manual intervention.
Interface defined here: https://v3.primevue.org/datatable/#pre_sort
> Restore default sort

- cypress/fixtures/generatedTestTemplate.js
- cypress/support/commands.js
- cypress/support/helper-functions/roar-sre/sreHelpers.js
The page refreshes when It picks the administration again after a refresh. So the solution we got with @ksmontville is to go back to switching to optional assignments.
Also reduced at least 1 min of sre and sre-es, since the game goes by time, we don't need to run the loop 80 times, I reduced it to 50. (33 is the max I have seen it uses {left-arrow} {write-arrow}, but kept it on 50 just in case)
We need this for deployment
> Fix test Open Admins

- src/composables/useUserType.js
- src/composables/useUserType.test.js
- src/constants/auth.js
- src/pages/HomeSelector.vue
This PR extends the `useUserType` composable introduced in #751 with the capability to check for super admin status.
n/a
n/a
> Extend `useUserType` with super admin capability check

- src/config/firebaseRoar.js
This PR fixes the App Check `debugToken` conditional for Cypress environment by leveraging `window.Cypress` for the environment determination as `NODE_ENV === 'test'` also evaluates to true when running unit tests, causing tests to fail: 
```
FAIL  src/composables/queries/useSurveyResponsesQuery.test.js [ src/composables/queries/useSurveyResponsesQuery.test.js ]
FAIL  src/composables/queries/useUserAssignmentsQuery.test.js [ src/composables/queries/useUserAssignmentsQuery.test.js ]
FAIL  src/composables/queries/useUserDataQuery.test.js [ src/composables/queries/useUserDataQuery.test.js ]
ReferenceError: Cypress is not defined
❯ setDebugToken src/config/firebaseRoar.js:17:17
15|   const debugToken =
16|     import.meta.env.NODE_ENV === 'test'
17|       ? Cypress.env('appCheckDebugToken')
| …
```
> Fix App Check `debugToken` conditional for Cypress environment

- src/components/tasks/ManageTasks.vue
- src/components/views/OfflineSettings.vue
- src/composables/queries/useAdministrationsListQuery.js
- src/composables/queries/useAdministrationsQuery.js
- src/composables/queries/useSurveyResponsesQuery.js
- src/composables/queries/useSurveyResponsesQuery.test.js
- src/composables/queries/useTasksQuery.js
- src/composables/queries/useTasksQuery.test.js
- src/composables/queries/useUserAssignmentsQuery.js
- src/composables/queries/useUserAssignmentsQuery.test.js
- src/constants/firebase.js
- src/constants/queryKeys.js
- src/helpers/query/assignments.js
- src/helpers/query/tasks.js
- src/helpers/query/utils.js
- src/pages/HomeAdministrator.vue
- src/pages/HomeParticipant.vue
- vitest.config.js
This PR migrates the `ParticipantHomepage` page to use new composable TanStack queries and mutations. 
n/a
n/a
Ref https://github.com/yeatmanlab/roar/issues/318
> Migrate Participant Homepage to composable TanStack queries

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roav-ran` to 1.0.30.
> Update ROAV-Ran version to 1.0.30

- cypress/e2e/partner-admin/default-tests/testProgressReportFiltering.spec.cy.js
- cypress/e2e/partner-admin/default-tests/testScoreReportFiltering.cy.js
- package-lock.json
- package.json
- src/router/index.js
> Adding Letter Canada to the Dashboard

- cypress/component/components/NavBar.cy.js
- src/components/NavBar.vue
Adding v-if to only show if the user is admin or super admin
> Fix - Students should not be able to see their demographic data

- src/pages/HomeAdministrator.vue
This PR fixes the loading of administrations when returning to the Administrator Homepage as described in #886
n/a
n/a
Ref https://github.com/yeatmanlab/roar/issues/318
Fixes #886
> Fix loading of administrator administrations

- src/pages/HomeParticipant.vue
- src/pages/HomeSelector.vue
This PR fixes the flashing loading states on the Participant homepage.
n/a
n/a
Ref https://github.com/yeatmanlab/roar/issues/318
Fixes #886
> Fix participant homepage loading state

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roar-multichoice` to 1.11.4.
> Update Multichoice version to 1.11.4

- src/composables/useFilteredTableData.js
- src/pages/HomeSelector.vue
- src/pages/ScoreReport.vue
This pull request addresses https://github.com/yeatmanlab/roar/issues/453.
**Major Changes:**
1. Created a computed property for `schoolOptions`, re-enabling filtering by school
2. Fix grade level filtering by casting user grade as a string for comparison (was previously failing due to type difference)
4. Update composable logic to better capture and use the initial state of the data table
5. Update watchers to trigger immediately (this resolves the issue with data not being populated after navigating away, and then back to, the score report)
> Fix Score Reports Not Populating Correctly

- .github/workflows/add-pull-request-to-qa-template.yml
This pull request introduces a GitHub action which automatically assigns pull requests to a given project based on label.
A new set of QA labels have been added to the dashboard repo. When a pull request is marked with one of:
- [qa] low priority
- [qa] medium priority
- [qa] high priority
That pull request will be automatically added to a QA project for review. This is a useful automation that will help the QA analysts organize their list of pull request that need testing.
The project URL and personal access token with scoped permissions are stored as repository secrets.
> enh/Auto Add Pull Requests to QA Template

- src/components/CardAdministration.vue
> Import PvChart on the card administration component

- .eslintrc.json
- package-lock.json
- src/components/CardAdministration.vue
- src/pages/LEVANTE/UserSurvey.vue
- vite.config.js
This PR enforces the optional (yet essential) ESLint rule `vue/no-undef-components` to ensure we catch undefined components as part of our linter checks. This PR also updates the `eslint-plugin-vue` package to its latest version.
n/a
n/a
> Enforce `vue/no-undef-components` ESLint rule

- cypress/e2e/partner-admin/default-tests/parentSignUpInvitationCode.cy.js
- src/assets/styles/routes/register.scss
- src/components/auth/RegisterChildren.vue
- src/components/auth/RegisterParent.vue
- src/pages/RegisterFamilyUsers.vue
- src/router/index.js
> Family Signup Form Styling Update

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roav-crowding` to 1.1.35.
> Update ROAV-Crowding version to 1.1.35

- src/components/GameTabs.vue
- src/translations/en/en-componentTranslations.json
- src/translations/en/us/en-us-componentTranslations.json
- src/translations/es/co/es-co-componentTranslations.json
- src/translations/es/es-componentTranslations.json
Ensure that external tasks requiring a record of a username open in a new tab instead of the same one. Additionally, display a message indicating that the task has been opened in a new tab and provide an option to click again.
THIS WAS REQUIRED -- ONLY the qualtrics-experience ROAR external task passes the participantID in the URL
This is important for the Microsoft study and future studies
> External ROAR tasks open in a new tab and display message

- .github/workflows/deploy-legacy-staging.yml
This PR adds the missing `DOTENV_PRIVATE_KEY` env variables to decrypt `dotenvx` environment configuration injected during the build process of the legacy staging site.
n/a
n/a
n/a
> Add missing private key for legacy staging deployments

- cypress/support/helper-functions/roam-apps/roamHelpers.js
- cypress/support/helper-functions/roar-letter/letterHelpers.js
- cypress/support/helper-functions/roar-multichoice/multichoiceHelpers.js
- cypress/support/helper-functions/roar-pa/paHelpers.js
- cypress/support/helper-functions/roar-sre/sreHelpers.js
- cypress/support/helper-functions/roar-swr/swrHelpers.js
- cypress/support/helper-functions/roar-syntax/syntaxHelpers.js
- cypress/support/helper-functions/roar-vocab/vocabHelpers.js
- firebase/admin/firestore.indexes.json
I noticed that the firestore index actions ([here](https://github.com/yeatmanlab/roar-dashboard/actions/runs/14229868872/job/39878277887)) were failing from @lucasxsong's recent PR #1090. This is because the new indexes were for `array-contains` queries on various `readOrgs` fields in the `assignments` collection. Instead of having separate composite indexes, we need to use single field indexes by moving these configurations to the `fieldOverrides` section of the file.
> Use fieldOverrides instead of composite indexes for assignments readOrgs

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roar-readaloud` to 1.2.1.
> Update Read Aloud version to 1.2.1

- package-lock.json
- package.json
This PR updates the version of `@bdelab/roav-mep` to 1.2.0.
> Update MEP version to 1.2.0

- package-lock.json
- package.json
This PR bumps the dashboard's `vue` version from v3.2.25 to v3.5 16.
> Bump `vue` from v3.2.25 to v3.5.16

- src/pages/ScoreReport.vue
This PR formats the start and completion date in the score report CSV export to display only the date (not the time).
> Display date only in CSV export of scores

- src/components/TaskPicker/TaskPicker.vue
Currently, the task picker allows a user to view only named variants via a toggle on the component. This affects the variants listed when browsing, however does not affect search results. This PR fixes that issue.
- Navigate to the task picker (on the create administration page)
- Switch to Individual tasks, and choose a taskId from the dropdown. SWR has named and unnamed variants.
- Notice that only named variants show.
- Uncheck the 'Show only named variants' toggle and note the list now includes variants with no name field populated.
- Search for the task ID using the search bar ('swr' or 'word')
- Notice that several variants show up without the name field populated.
- Reenable the named variants toggle.
- Notice the search results filter out unnamed variants automatically. 
What …
> [FIX] Filter search results for named variants

- src/pages/ProgressReport.vue
- src/pages/ScoreReport.vue
In score and progress reports, display the user's grade at time of assignment, rather than the user's current grade.
> Set user grade in score reports from the assignment data rather than user data

- apps/dashboard/cypress/support/utils.js
This PR updates the `package.json` path used in assessment E2E test to set run conditions. 
For the time being, no changes are made to the existing semver-range string comparison to decide whether to run assessment E2E tests. We should however consider changing this to compare resolved versions from package-lock.json to avoid semver-range masking.
> Fix package lookup path for assessment E2E testing condition

- apps/dashboard/src/components/reports/SubscoreTable.vue
- apps/dashboard/src/components/reports/TableScoreTag.vue
- apps/dashboard/src/helpers/reports.js
- apps/dashboard/src/pages/ScoreReport.vue
This PR updates ROAM fluency scores and variables according to the changes made in ROAM's newest version 1.2.23. 
Changes:
**1.2.23**
Score report
- Tasks with recruitment = responseModality will not show raw scores, only the assessed circle. Other variants are not affected and will continue to show raw score 
Subscore table
- Free Choice and Multiple Choice score now returns rawScore instead of roamScore.
- Tooltips show raw score, num correct, num incorrect, and num attempted. 
- Exported tables contain the tooltip values. 
Handles score report for versions  < 1.2.14 and 1.2.23 (no student data between 1.2.15 and 1.2.22)
**1.2.14** 
- Tooltips show numCorrect (totalNumCorrect) and numAttempted (numAttempted). No raw score is shown, regardless of response modality. (empty tag = old …
> Update ROAM fluency scores 
